
default: &default
  adapter: postgresql
  encoding: unicode

  pool: 5

development:
  <<: *default
  database: Pandabook_development

test:
  <<: *default
  database: Pandabook_test

production:
  <<: *default
  database: Pandabook_production
  username: Pandabook
  password: <%= ENV['PANDABOOK_DATABASE_PASSWORD'] %>
